name: ZombieApocalypse
version: 1.0
main: com.nonkungch.zombieapocalypse.ZombieApocalypse
api-version: 1.19
description: The complete Zombie Apocalypse plugin (Phases 1-7).
commands:
  cureme:
    description: Cures the player of the infection.
    usage: /cureme
  safezone:
    description: Manages safe zones.
    usage: /safezone <create>